language: node_js
node_js:
  - '0.12'
  - '0.10'

before_install:
  - 'npm install -g grunt-cli'

after_script:
  - 'find ./coverage -name lcov.info -exec cat {} \; | ./node_modules/coveralls/bin/coveralls.js'
